### ISSUE TITLE
Enable easier importing

### ISSUE THREAD

**Issue by taddison** [petervandivier/ag-patch-buddy#3]
The module manifest doesn't match the folder name, so the following doesn't work:

```powershell
Import-Module .\ag-patch-buddy
```

Instead, I need to reference the module manifest directly:

```powershell
Import-Module .\ag-patch-buddy\AOAGPatchBuddy.psd1
```

Could fix this by making the psd1 file name the same as the repo (`ag-patch-buddy.psd1`) or nesting the module in a folder with the same name as a manifest (`\AOAGPatchBuddy`).

**Comment by petervandivier** [comment]
🤔 clearly I put lots of fore planning into this repo. I’m not married to any naming conventions atm, but my first instinct is to hold any piecemeal renames until it’s sensible and useable as a unit. 

I’m inclined to vote for the workaround for the time being. You can also specify the target folder name at clone time `git clone git@github.com:petervandivier/ag-patch-buddy.git AOAGPatchBuddy`

I think the reason it hasn’t bothered before until now is b/c the module is rough enough that it’s not plug-and-play so I end up just using the functions as one offs whenever I need them. Of course I’m open to any change that improves usability though.

**Comment by taddison** [comment]
Rename on clone is so much easier!  I have a suggestion for the readme in that case...

**Comment by taddison** [comment]
PR to add that hint to the readme #4
